name: CI Orchestrator

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  semver:
    needs: setup
    uses: ./.github/workflows/semver.yml

  test:
    needs: [setup, semver]
    uses: ./.github/workflows/test.yml
    with:
      packages-json: ${{ needs.setup.outputs.packages-json }}

  sonarcloud:
    needs: test
    uses: ./.github/workflows/sonar_scan.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
