name: SemVer

on:
  workflow_call:

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine version bump
        id: semver
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "PR title: $PR_TITLE"
          bump="patch"
          if [[ "$PR_TITLE" == MAJOR* ]]; then bump="major"; fi
          if [[ "$PR_TITLE" == MINOR* ]]; then bump="minor"; fi
          echo "bump=$bump" >> $GITHUB_OUTPUT

      - name: Run Lerna Version
        run: npx lerna version ${{ steps.semver.outputs.bump }} --yes --no-push
