name: SonarCloud

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: "SonarCloud token"
        required: true
    inputs:
      github_token:
        description: "GitHub token to update PR status"
        required: true
        type: string

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Download coverage artifacts
      - name: Download container coverage
        uses: actions/download-artifact@v4
        with:
          name: container-coverage
          path: packages/container/coverage

      - name: Download remote coverage
        uses: actions/download-artifact@v4
        with:
          name: remote-coverage
          path: packages/remote/coverage

      - name: Download footer coverage
        uses: actions/download-artifact@v4
        with:
          name: footer-coverage
          path: packages/footer/coverage

      # 4️⃣ Run SonarCloud scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
        with:
          args: >
            -Dsonar.organization=rahulnikam2002
            -Dsonar.projectKey=rahulnikam2002_micro-frontend-module-federation
            -Dsonar.projectName=micro-frontend-module-federation
            -Dsonar.sources=packages/container/src,packages/remote/src,packages/footer/src
            -Dsonar.tests=packages/container/src,packages/remote/src,packages/footer/src
            -Dsonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx
            -Dsonar.exclusions=**/*.d.ts,**/jest.config.js,**/jest.config.ts,**/webpack.config.js,**/webpack.config.ts,**/__mocks__/**,**/node_modules/**
            -Dsonar.javascript.lcov.reportPaths=packages/container/coverage/lcov.info,packages/remote/coverage/lcov.info,packages/footer/coverage/lcov.info

      # 5️⃣ Check SonarCloud Quality Gate
      - name: Check SonarCloud Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
